export const voucherABI = [
  {
    inputs: [{ internalType: "address", name: "_pmToken", type: "address" }, { internalType: "address", name: "_feeCollector", type: "address" }],
    stateMutability: "nonpayable",
    type: "constructor"
  },
  { inputs: [{ internalType: "address", name: "_merchant", type: "address" }], name: "approveMerchant", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "address", name: "", type: "address" }], name: "approvedMerchants", outputs: [{ internalType: "bool", name: "", type: "bool" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "uint256", name: "_voucherId", type: "uint256" }, { internalType: "address", name: "_to", type: "address" }], name: "assignVoucher", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "uint256", name: "_voucherId", type: "uint256" }], name: "cancelVoucher", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "string", name: "", type: "string" }], name: "codeToVoucherId", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  {
    inputs: [
      { internalType: "string", name: "_code", type: "string" },
      { internalType: "string", name: "_name", type: "string" },
      { internalType: "uint256", name: "_value", type: "uint256" },
      { internalType: "uint8", name: "_voucherType", type: "uint8" },
      { internalType: "uint256", name: "_expiryDate", type: "uint256" },
      { internalType: "bool", name: "_isTransferable", type: "bool" }
    ],
    name: "createVoucher",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function"
  },
  { inputs: [], name: "feeCollector", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "address", name: "_merchant", type: "address" }], name: "getMerchantVouchers", outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "address", name: "_user", type: "address" }], name: "getUserVouchers", outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "string", name: "_code", type: "string" }], name: "getVoucherByCode", outputs: [{ components: [{ internalType: "uint256", name: "id", type: "uint256" }, { internalType: "address", name: "creator", type: "address" }, { internalType: "address", name: "assignedTo", type: "address" }, { internalType: "string", name: "code", type: "string" }, { internalType: "string", name: "name", type: "string" }, { internalType: "uint256", name: "value", type: "uint256" }, { internalType: "uint8", name: "voucherType", type: "uint8" }, { internalType: "uint8", name: "status", type: "uint8" }, { internalType: "uint256", name: "createdAt", type: "uint256" }, { internalType: "uint256", name: "expiryDate", type: "uint256" }, { internalType: "uint256", name: "usedAt", type: "uint256" }, { internalType: "bool", name: "isTransferable", type: "bool" }], internalType: "struct PMVoucher.Voucher", name: "", type: "tuple" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "string", name: "_code", type: "string" }], name: "isVoucherValid", outputs: [{ internalType: "bool", name: "", type: "bool" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "address", name: "", type: "address" }, { internalType: "uint256", name: "", type: "uint256" }], name: "merchantCreatedVouchers", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "merchantCreationFee", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "nextVoucherId", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "owner", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "paused", outputs: [{ internalType: "bool", name: "", type: "bool" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "pmToken", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "string", name: "_code", type: "string" }], name: "redeemVoucher", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "renounceOwnership", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "address", name: "_merchant", type: "address" }], name: "revokeMerchant", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "uint256", name: "_fee", type: "uint256" }], name: "setCreationFee", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "address", name: "_feeCollector", type: "address" }], name: "setFeeCollector", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "bool", name: "_paused", type: "bool" }], name: "setPaused", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "address", name: "_to", type: "address" }], name: "transferOwnership", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "uint256", name: "_voucherId", type: "uint256" }, { internalType: "address", name: "_to", type: "address" }], name: "transferVoucher", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "address", name: "", type: "address" }, { internalType: "uint256", name: "", type: "uint256" }], name: "userVouchers", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "uint256", name: "", type: "uint256" }], name: "vouchers", outputs: [{ internalType: "uint256", name: "id", type: "uint256" }, { internalType: "address", name: "creator", type: "address" }, { internalType: "address", name: "assignedTo", type: "address" }, { internalType: "string", name: "code", type: "string" }, { internalType: "string", name: "name", type: "string" }, { internalType: "uint256", name: "value", type: "uint256" }, { internalType: "uint8", name: "voucherType", type: "uint8" }, { internalType: "uint8", name: "status", type: "uint8" }, { internalType: "uint256", name: "createdAt", type: "uint256" }, { internalType: "uint256", name: "expiryDate", type: "uint256" }, { internalType: "uint256", name: "usedAt", type: "uint256" }, { internalType: "bool", name: "isTransferable", type: "bool" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "address", name: "_token", type: "address" }, { internalType: "uint256", name: "_amount", type: "uint256" }], name: "withdrawTokens", outputs: [], stateMutability: "nonpayable", type: "function" },
  { anonymous: false, inputs: [{ indexed: false, internalType: "uint256", name: "newFee", type: "uint256" }], name: "CreationFeeUpdated", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "address", name: "merchant", type: "address" }], name: "MerchantApproved", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "address", name: "merchant", type: "address" }], name: "MerchantRevoked", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "address", name: "previousOwner", type: "address" }, { indexed: true, internalType: "address", name: "newOwner", type: "address" }], name: "OwnershipTransferred", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "uint256", name: "id", type: "uint256" }, { indexed: true, internalType: "address", name: "assignedTo", type: "address" }], name: "VoucherAssigned", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "uint256", name: "id", type: "uint256" }], name: "VoucherCancelled", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "uint256", name: "id", type: "uint256" }, { indexed: true, internalType: "address", name: "creator", type: "address" }, { indexed: false, internalType: "string", name: "code", type: "string" }, { indexed: false, internalType: "uint256", name: "value", type: "uint256" }, { indexed: false, internalType: "uint8", name: "voucherType", type: "uint8" }, { indexed: false, internalType: "uint256", name: "expiryDate", type: "uint256" }], name: "VoucherCreated", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "uint256", name: "id", type: "uint256" }, { indexed: true, internalType: "address", name: "redeemedBy", type: "address" }, { indexed: false, internalType: "uint256", name: "value", type: "uint256" }], name: "VoucherRedeemed", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "uint256", name: "id", type: "uint256" }, { indexed: true, internalType: "address", name: "from", type: "address" }, { indexed: true, internalType: "address", name: "to", type: "address" }], name: "VoucherTransferred", type: "event" }
] as const;
